use new_schema;
CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID INT(6),
  LAST_NAME VARCHAR(25),
  JOB_ID VARCHAR(10),
  SALARY NUMERIC(8,2),
  COMM_PCT NUMERIC(4,2),
  MGR_ID INT(6),
  DEPARTMENT_ID INT(4)
);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY, COMM_PCT, MGR_ID, DEPARTMENT_ID) VALUES
(1, 'King', 'President', 5000.00, NULL, NULL, 10),
(2, 'Scott', 'Analyst', 3000.00, NULL, 1, 20),
(3, 'Adams', 'Clerk', 1100.00, NULL, 2, 20),
(4, 'Jones', 'Manager', 2975.00, NULL, 1, 20),
(5, 'Ford', 'Analyst', 3000.00, NULL, 4, 20);

INSERT INTO EMPLOYEE (EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY, COMM_PCT, MGR_ID, DEPARTMENT_ID) VALUES
(6, 'Smith', 'Clerk', 800.00, NULL, 2, 20),
(7, 'Allen', 'Salesman', 1600.00, 0.10, 4, 30),
(8, 'Ward', 'Salesman', 1250.00, 0.10, 4, 30),
(9, 'Clark', 'Manager', 2450.00, NULL, 1, 10),
(10, 'Miller', 'Clerk', 1300.00, NULL, 9, 10);

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE LAST_NAME = 'King';

SELECT DISTINCT JOB_ID AS JOB_TITLE FROM EMPLOYEE;
SELECT LAST_NAME, SALARY, (SALARY+300) AS 'Increased Salary' FROM EMPLOYEE;

SELECT LAST_NAME, SALARY, (SALARY*12+100) AS 'Annual Compensation' FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE COMM_PCT IS NOT NULL;
SELECT * FROM EMPLOYEE WHERE COMM_PCT IS NULL;
SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY FROM EMPLOYEE WHERE SALARY > 5000;

SELECT LAST_NAME, SALARY FROM EMPLOYEE WHERE SALARY BETWEEN 4000 AND 7000;

SELECT * FROM EMPLOYEE WHERE SALARY IN (6000, 6500, 7000);

SELECT * FROM EMPLOYEE WHERE DEPARTMENT_ID IN (10, 20, 30, 50);

SELECT * FROM EMPLOYEE WHERE SALARY <> 5000;
SELECT * FROM EMPLOYEE WHERE JOB_ID = 'CLERK';
UPDATE EMPLOYEE SET JOB_ID = 'Grade_A' WHERE SALARY > 5000;
SELECT * FROM EMPLOYEE;
SELECT *FROM EMPLOYEE WHERE JOB_ID IN ('CLERK', 'PROGRAMMER', 'ASSISTANT');

SELECT *FROM EMPLOYEE WHERE JOB_ID = 'CLERK' AND SALARY < 3000;

SELECT LAST_NAME, MGR_ID FROM EMPLOYEE WHERE SALARY > 3000 AND MGR_ID = 101;